{* Embedded information-collection lead form, mirroring the reference markup.
   Param: form_object_id (the Lead form content object). *}
{def $lf_id = first_set($form_object_id, 0)}
{def $lf_name = concat('information_collection_', $lf_id)}
<div         class="ngenhancedlink-field" ><form name="{$lf_name}" method="post" action={concat('/content/action')|ezurl(no)} data-gtm-event-prefix="form-lead" class="embed-form js-form-embed" novalidate><div class="form-wrapper"><div class="form-group sender-first-name"><label for="{$lf_name}_sender_first_name_value" class="form-label required">First name                <span aria-hidden="true">*</span><span class="sr-only">Mandatory field</span></label><input class="form-control" type="text"
id="{$lf_name}_sender_first_name_value" name="{$lf_name}[sender_first_name][value]" required="required"
autocomplete="given-name"         aria-invalid="false" aria-errormessage="error-{$lf_name}_sender_first_name_value"    /><span id="error-{$lf_name}_sender_first_name_value" class="error-message">Enter a valid First name</span></div><div class="form-group sender-middle-name"><label for="{$lf_name}_sender_middle_name_value" class="form-label">Middle name        </label><input class="form-control" type="text"
id="{$lf_name}_sender_middle_name_value" name="{$lf_name}[sender_middle_name][value]" tabindex="-1"
aria-invalid="false" aria-errormessage="error-{$lf_name}_sender_middle_name_value"    /><span id="error-{$lf_name}_sender_middle_name_value" class="error-message">Enter a valid Middle name</span></div><div class="form-group sender-last-name"><label for="{$lf_name}_sender_last_name_value" class="form-label required">Last name                <span aria-hidden="true">*</span><span class="sr-only">Mandatory field</span></label><input class="form-control" type="text"
id="{$lf_name}_sender_last_name_value" name="{$lf_name}[sender_last_name][value]" required="required"
autocomplete="family-name"         aria-invalid="false" aria-errormessage="error-{$lf_name}_sender_last_name_value"    /><span id="error-{$lf_name}_sender_last_name_value" class="error-message">Enter a valid Last name</span></div><div class="form-group sender-email"><label for="{$lf_name}_sender_email_value" class="form-label required">E-mail                <span aria-hidden="true">*</span><span class="sr-only">Mandatory field</span></label><input class="form-control" type="email"
id="{$lf_name}_sender_email_value" name="{$lf_name}[sender_email][value]" required="required"
autocomplete="email"         aria-invalid="false" aria-errormessage="error-{$lf_name}_sender_email_value"    /><span id="error-{$lf_name}_sender_email_value" class="error-message">Enter a valid E-mail</span></div><div class="form-group sender-message"><label for="{$lf_name}_sender_message_value" class="form-label">Message        </label><textarea class="form-control" id="{$lf_name}_sender_message_value" name="{$lf_name}[sender_message][value]" rows="5"></textarea></div><div class="form-group form-check gdpr-consent"><input type="checkbox" class="form-check-input" id="{$lf_name}_gdpr_consent_value" name="{$lf_name}[gdpr_consent][value]" required="required" value="1" /><label class="form-label" for={$lf_name}_gdpr_consent_value aria-invalid="false"
aria-errormessage="error-{$lf_name}_gdpr_consent_value" /><p>I have read <a href={'/Fit-Healthy/Privacy-Policy'|ezurl}>Privacy Policy</a> and agree to its terms.</p></label><span id="error-{$lf_name}_gdpr_consent_value" class="error-message">GDPR Consent not checked</span></div><div class="form-group form-check newsletter-1-consent"><input type="checkbox" class="form-check-input" id="{$lf_name}_newsletter_1_consent_value" name="{$lf_name}[newsletter_1_consent][value]" value="1" /><label class="form-label" for={$lf_name}_newsletter_1_consent_value aria-invalid="false"
aria-errormessage="error-{$lf_name}_newsletter_1_consent_value" /><p>I consent to receiving marketing and promotional materials. I understand that I can unsubscribe at any time.</p></label><span id="error-{$lf_name}_newsletter_1_consent_value" class="error-message">Newsletter 1 Consent not checked</span></div><input class="form-control" type="hidden"
id="{$lf_name}_referer_value" name="{$lf_name}[referer][value]" value=""
/><div class="form-submit"><button type="submit" class="btn btn-primary">Send form</button></div></div><input class="form-control" type="hidden"
id="{$lf_name}_content_id" name="{$lf_name}[content_id]"
value="{$lf_id}"                    /><input class="form-control" type="hidden"
id="{$lf_name}_content_type_id" name="{$lf_name}[content_type_id]"
value="118"                    /><input class="form-control" type="hidden"
id="{$lf_name}_discriminator" name="{$lf_name}[discriminator]"
value="{$lf_id}"                    /></form></div>
{undef $lf_id $lf_name}
