<?php /* #?ini charset="utf-8"?

; Media design template overrides for the "site" siteaccess.
; Generated by ai/bin/one/generate_sevenx_themes_media_site_override_ini.py
; Do not edit by hand — rerun the generator if templates are added.

[node/view/full#frontpage]
Source=node/view/full.tpl
MatchFile=node/view/full/full_frontpage.tpl
Subdir=templates
Match[class_identifier]=frontpage
Priority=1

[node/view/full#ng_article]
Source=node/view/full.tpl
MatchFile=node/view/full/full_ng_article.tpl
Subdir=templates
Match[class_identifier]=ng_article
Priority=1

[node/view/full#ng_audio]
Source=node/view/full.tpl
MatchFile=node/view/full/full_ng_audio.tpl
Subdir=templates
Match[class_identifier]=ng_audio
Priority=1

[node/view/full#ng_blog_post]
Source=node/view/full.tpl
MatchFile=node/view/full/full_ng_blog_post.tpl
Subdir=templates
Match[class_identifier]=ng_blog_post
Priority=1

[node/view/full#ng_category]
Source=node/view/full.tpl
MatchFile=node/view/full/full_ng_category.tpl
Subdir=templates
Match[class_identifier]=ng_category
Priority=1

[node/view/full#ng_contact_form]
Source=node/view/full.tpl
MatchFile=node/view/full/full_ng_contact_form.tpl
Subdir=templates
Match[class_identifier]=ng_contact_form
Priority=1

[node/view/full#ng_container]
Source=node/view/full.tpl
MatchFile=node/view/full/full_ng_container.tpl
Subdir=templates
Match[class_identifier]=ng_container
Priority=1

[node/view/full#ng_frontpage]
Source=node/view/full.tpl
MatchFile=node/view/full/full_ng_frontpage.tpl
Subdir=templates
Match[class_identifier]=ng_frontpage
Priority=1

[node/view/full#ng_gallery]
Source=node/view/full.tpl
MatchFile=node/view/full/full_ng_gallery.tpl
Subdir=templates
Match[class_identifier]=ng_gallery
Priority=1

[node/view/full#ng_htmlbox]
Source=node/view/full.tpl
MatchFile=node/view/full/full_ng_htmlbox.tpl
Subdir=templates
Match[class_identifier]=ng_htmlbox
Priority=1

[node/view/full#ng_job_position]
Source=node/view/full.tpl
MatchFile=node/view/full/full_ng_job_position.tpl
Subdir=templates
Match[class_identifier]=ng_job_position
Priority=1

[node/view/full#ng_landing_page]
Source=node/view/full.tpl
MatchFile=node/view/full/full_ng_landing_page.tpl
Subdir=templates
Match[class_identifier]=ng_landing_page
Priority=1

[node/view/full#ng_news]
Source=node/view/full.tpl
MatchFile=node/view/full/full_ng_news.tpl
Subdir=templates
Match[class_identifier]=ng_news
Priority=1

[node/view/full#ng_person]
Source=node/view/full.tpl
MatchFile=node/view/full/full_ng_person.tpl
Subdir=templates
Match[class_identifier]=ng_person
Priority=1

[node/view/full#ng_recipe]
Source=node/view/full.tpl
MatchFile=node/view/full/full_ng_recipe.tpl
Subdir=templates
Match[class_identifier]=ng_recipe
Priority=1

[node/view/full#ng_topic]
Source=node/view/full.tpl
MatchFile=node/view/full/full_ng_topic.tpl
Subdir=templates
Match[class_identifier]=ng_topic
Priority=1

[node/view/full#ng_video]
Source=node/view/full.tpl
MatchFile=node/view/full/full_ng_video.tpl
Subdir=templates
Match[class_identifier]=ng_video
Priority=1

[node/view/line#file]
Source=node/view/line.tpl
MatchFile=node/view/line/line_file.tpl
Subdir=templates
Match[class_identifier]=file
Priority=1

[node/view/line#ng_article]
Source=node/view/line.tpl
MatchFile=node/view/line/line_ng_article.tpl
Subdir=templates
Match[class_identifier]=ng_article
Priority=1

[node/view/line#ng_audio]
Source=node/view/line.tpl
MatchFile=node/view/line/line_ng_audio.tpl
Subdir=templates
Match[class_identifier]=ng_audio
Priority=1

[node/view/line#ng_banner]
Source=node/view/line.tpl
MatchFile=node/view/line/line_ng_banner.tpl
Subdir=templates
Match[class_identifier]=ng_banner
Priority=1

[node/view/line#ng_blog_post]
Source=node/view/line.tpl
MatchFile=node/view/line/line_ng_blog_post.tpl
Subdir=templates
Match[class_identifier]=ng_blog_post
Priority=1

[node/view/line#ng_category]
Source=node/view/line.tpl
MatchFile=node/view/line/line_ng_category.tpl
Subdir=templates
Match[class_identifier]=ng_category
Priority=1

[node/view/line#ng_contact_form]
Source=node/view/line.tpl
MatchFile=node/view/line/line_ng_contact_form.tpl
Subdir=templates
Match[class_identifier]=ng_contact_form
Priority=1

[node/view/line#ng_gallery]
Source=node/view/line.tpl
MatchFile=node/view/line/line_ng_gallery.tpl
Subdir=templates
Match[class_identifier]=ng_gallery
Priority=1

[node/view/line#ng_landing_page]
Source=node/view/line.tpl
MatchFile=node/view/line/line_ng_landing_page.tpl
Subdir=templates
Match[class_identifier]=ng_landing_page
Priority=1

[node/view/line#ng_news]
Source=node/view/line.tpl
MatchFile=node/view/line/line_ng_news.tpl
Subdir=templates
Match[class_identifier]=ng_news
Priority=1

[node/view/line#ng_recipe]
Source=node/view/line.tpl
MatchFile=node/view/line/line_ng_recipe.tpl
Subdir=templates
Match[class_identifier]=ng_recipe
Priority=1

[node/view/line#ng_video]
Source=node/view/line.tpl
MatchFile=node/view/line/line_ng_video.tpl
Subdir=templates
Match[class_identifier]=ng_video
Priority=1

[node/view/standard#file]
Source=node/view/standard.tpl
MatchFile=node/view/standard/standard_file.tpl
Subdir=templates
Match[class_identifier]=file
Priority=1

[node/view/standard#image]
Source=node/view/standard.tpl
MatchFile=node/view/standard/standard_image.tpl
Subdir=templates
Match[class_identifier]=image
Priority=1

[node/view/standard#ng_article]
Source=node/view/standard.tpl
MatchFile=node/view/standard/standard_ng_article.tpl
Subdir=templates
Match[class_identifier]=ng_article
Priority=1

[node/view/standard#ng_audio]
Source=node/view/standard.tpl
MatchFile=node/view/standard/standard_ng_audio.tpl
Subdir=templates
Match[class_identifier]=ng_audio
Priority=1

[node/view/standard#ng_banner]
Source=node/view/standard.tpl
MatchFile=node/view/standard/standard_ng_banner.tpl
Subdir=templates
Match[class_identifier]=ng_banner
Priority=1

[node/view/standard#ng_blog_post]
Source=node/view/standard.tpl
MatchFile=node/view/standard/standard_ng_blog_post.tpl
Subdir=templates
Match[class_identifier]=ng_blog_post
Priority=1

[node/view/standard#ng_category]
Source=node/view/standard.tpl
MatchFile=node/view/standard/standard_ng_category.tpl
Subdir=templates
Match[class_identifier]=ng_category
Priority=1

[node/view/standard#ng_contact_form]
Source=node/view/standard.tpl
MatchFile=node/view/standard/standard_ng_contact_form.tpl
Subdir=templates
Match[class_identifier]=ng_contact_form
Priority=1

[node/view/standard#ng_frontpage]
Source=node/view/standard.tpl
MatchFile=node/view/standard/standard_ng_frontpage.tpl
Subdir=templates
Match[class_identifier]=ng_frontpage
Priority=1

[node/view/standard#ng_gallery]
Source=node/view/standard.tpl
MatchFile=node/view/standard/standard_ng_gallery.tpl
Subdir=templates
Match[class_identifier]=ng_gallery
Priority=1

[node/view/standard#ng_htmlbox]
Source=node/view/standard.tpl
MatchFile=node/view/standard/standard_ng_htmlbox.tpl
Subdir=templates
Match[class_identifier]=ng_htmlbox
Priority=1

[node/view/standard#ng_landing_page]
Source=node/view/standard.tpl
MatchFile=node/view/standard/standard_ng_landing_page.tpl
Subdir=templates
Match[class_identifier]=ng_landing_page
Priority=1

[node/view/standard#ng_news]
Source=node/view/standard.tpl
MatchFile=node/view/standard/standard_ng_news.tpl
Subdir=templates
Match[class_identifier]=ng_news
Priority=1

[node/view/standard#ng_recipe]
Source=node/view/standard.tpl
MatchFile=node/view/standard/standard_ng_recipe.tpl
Subdir=templates
Match[class_identifier]=ng_recipe
Priority=1

[node/view/standard#ng_video]
Source=node/view/standard.tpl
MatchFile=node/view/standard/standard_ng_video.tpl
Subdir=templates
Match[class_identifier]=ng_video
Priority=1

[node/view/embed#ng_article]
Source=node/view/embed.tpl
MatchFile=node/view/embed/embed_ng_article.tpl
Subdir=templates
Match[class_identifier]=ng_article
Priority=1

[node/view/embed#ng_audio]
Source=node/view/embed.tpl
MatchFile=node/view/embed/embed_ng_audio.tpl
Subdir=templates
Match[class_identifier]=ng_audio
Priority=1

[node/view/embed#ng_banner]
Source=node/view/embed.tpl
MatchFile=node/view/embed/embed_ng_banner.tpl
Subdir=templates
Match[class_identifier]=ng_banner
Priority=1

[node/view/embed#ng_blog_post]
Source=node/view/embed.tpl
MatchFile=node/view/embed/embed_ng_blog_post.tpl
Subdir=templates
Match[class_identifier]=ng_blog_post
Priority=1

[node/view/embed#ng_category]
Source=node/view/embed.tpl
MatchFile=node/view/embed/embed_ng_category.tpl
Subdir=templates
Match[class_identifier]=ng_category
Priority=1

[node/view/embed#ng_contact_form]
Source=node/view/embed.tpl
MatchFile=node/view/embed/embed_ng_contact_form.tpl
Subdir=templates
Match[class_identifier]=ng_contact_form
Priority=1

[node/view/embed#ng_frontpage]
Source=node/view/embed.tpl
MatchFile=node/view/embed/embed_ng_frontpage.tpl
Subdir=templates
Match[class_identifier]=ng_frontpage
Priority=1

[node/view/embed#ng_gallery]
Source=node/view/embed.tpl
MatchFile=node/view/embed/embed_ng_gallery.tpl
Subdir=templates
Match[class_identifier]=ng_gallery
Priority=1

[node/view/embed#ng_htmlbox]
Source=node/view/embed.tpl
MatchFile=node/view/embed/embed_ng_htmlbox.tpl
Subdir=templates
Match[class_identifier]=ng_htmlbox
Priority=1

[node/view/embed#ng_landing_page]
Source=node/view/embed.tpl
MatchFile=node/view/embed/embed_ng_landing_page.tpl
Subdir=templates
Match[class_identifier]=ng_landing_page
Priority=1

[node/view/embed#ng_news]
Source=node/view/embed.tpl
MatchFile=node/view/embed/embed_ng_news.tpl
Subdir=templates
Match[class_identifier]=ng_news
Priority=1

[node/view/embed#ng_shortcut]
Source=node/view/embed.tpl
MatchFile=node/view/embed/embed_ng_shortcut.tpl
Subdir=templates
Match[class_identifier]=ng_shortcut
Priority=1

[node/view/embed#ng_video]
Source=node/view/embed.tpl
MatchFile=node/view/embed/embed_ng_video.tpl
Subdir=templates
Match[class_identifier]=ng_video
Priority=1

[node/view/payload#ng_contact_form]
Source=node/view/payload.tpl
MatchFile=node/view/payload/payload.tpl
Subdir=templates
Match[class_identifier]=ng_contact_form
Priority=1

[content/view/embed#file]
Source=content/view/embed.tpl
MatchFile=content/view/embed/embed_file.tpl
Subdir=templates
Match[class_identifier]=file
Priority=1

[content/view/embed#image]
Source=content/view/embed.tpl
MatchFile=content/view/embed/embed_image.tpl
Subdir=templates
Match[class_identifier]=image
Priority=1

*/ ?>
