{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{set $classification = cond( and(is_set( $align ), $align|ne('') ), concat( $classification|first_set(''), ' text-', $align ), $classification|first_set('') )}
<p{if $classification|trim} class="{$classification|wash}"{/if}>
{if eq( $content|first_set('')|trim(), '' )}&nbsp;{else}{$content}{/if}
</p>