{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{if not(is_set($classification))}{set $classification = ''}{/if}
{set $classification = cond( and(is_set($align), $align|ne('')), concat($classification, ' text-', $align), $classification )}
<p{if $classification|trim} class="{$classification|wash}"{/if}>
{if not(is_set($content))}{set $content = ''}{/if}
{if eq($content|trim(), '')}&nbsp;{else}{$content}{/if}
</p>